---
homeassistant:
  customize:
    automation.alert_home_assistant:
      icon: mdi:bell-cancel

automation:
  - id: alert_home_assistant
    alias: Alert - Home Assistant
    mode: single
    trigger:
      - id: shutdown
        platform: homeassistant
        event: shutdown
      - id: start
        platform: homeassistant
        event: start
    action:
      - service: script.alert_send
        data:
          tag: automation.alert_home_assistant
          message: |
            {% if trigger.id == "shutdown" %}
              Home Assistant is shutting down
            {% elif trigger.id == "start" %}
              Home Assistant has started
            {% endif %}
