---
homeassistant:
  customize:
    automation.alert_intrusion:
      icon: mdi:shield-alert
automation:
  - id: alert_intrusion
    alias: Alert - Intrusion
    mode: single
    trigger:
      - id: location_detected
        entity_id:
          - sensor.latest_location
        platform: state
        not_to:
          - Away
          - Unknown
    condition:
      - entity_id: person.djhanggi
        condition: state
        state: not_home
    action:
      - service: notify.mobile_app_scarif
        data:
          message: request_location_update
      - delay:
          seconds: 3
      - condition: '{{ is_state("person.djhanggi", "not_home") }}'
      - service: script.alert_send
        data:
          message: Motion detected while not home
          tag: automation.alert_intrusion
      - scene: scene.away_return_scene
