---
homeassistant:
  customize:
    automation.presence_kitchen_stove:
      icon: mdi:stove
    sensor.kitchen_temperature_derivative:
      icon: mdi:thermometer

sensor:
  - name: Kitchen Temperature Derivative
    platform: derivative
    source: sensor.aqara_temperature_kitchen_temperature
    time_window: "00:02:00"
    unit_time: min

automation:
  - id: presence_kitchen_stove
    alias: Presence - Kitchen Stove
    mode: single
    trigger:
      - id: temperature_change
        platform: state
        entity_id: sensor.kitchen_temperature_derivative
    condition:
      - condition: numeric_state
        entity_id: sensor.kitchen_temperature_derivative
        above: 0.02
    action:
      - repeat:
          sequence:
            - if:
                - '{{ is_state("binary_sensor.aqara_motion_kitchen", "off") }}'
              then:
                - service: notify.mobile_app_cantonica
                  data:
                    data:
                      tag: automation.presence_kitchen_stove
                    message: Stove may be running!
                - repeat:
                    sequence:
                      - service: switch.toggle
                        target:
                          entity_id: switch.kitchen_lights
                    count: 2
            - delay:
                minutes: 2
          until:
            - '{{ states("sensor.kitchen_temperature_derivative") | float <= 0
              }}'
      - service: notify.mobile_app_cantonica
        data:
          data:
            tag: automation.presence_kitchen_stove
          message: clear_notification
