---
homeassistant:
  customize:
    automation.alert_pagerduty:
      icon: mdi:alert

automation:
  - id: alert_pagerduty
    alias: Alert - PagerDuty
    trigger:
      - platform: webhook
        variables:
          acknowledge_action_id: ACK_{{ trigger.json.event.id }}
        webhook_id: !secret webhook_pagerduty_id
    condition:
      - condition: state
        entity_id: person.djhanggi
        state: home
    action:
      - service: notify.mobile_app_scarif
        data:
          data:
            command: normal
          message: command_ringer_mode
      - service: notify.notify
        data:
          data:
            actions:
              - title: Acknowledge
                action: "{{ acknowledge_action_id }}"
            tag: automation.pagerduty_alert
          message: "PagerDuty: {{ trigger.json.event.data.message }}"
      - service: switch.turn_on
        target:
          entity_id: switch.party_lights
      - wait_for_trigger:
          - platform: event
            event_data:
              action: "{{ acknowledge_action_id }}"
            event_type: mobile_app_notification_action
      - service: switch.turn_off
        target:
          entity_id: switch.party_lights
      - service: notify.notify
        data:
          data:
            tag: automation.pagerduty_alert
          message: clear_notification
