---
homeassistant:
  customize:
    automaiton.pagerduty_alert:
      icon: mdi:alert

automation:
  - id: pagerduty_alert
    alias: PagerDuty Alert
    trigger:
      - platform: webhook
        variables:
          acknowledge_action_id: ACK_{{ trigger.json.event.id }}
        webhook_id: !secret webhook_pagerduty_id
    condition:
      - condition: state
        entity_id: person.djhanggi
        state: home
      - condition: state
        entity_id: sensor.phase_of_day
        state: Daytime
    action:
      - service: notify.mobile_app_scarif
        data:
          data:
            command: normal
          message: command_ringer_mode
      - service: notify.notify
        data:
          data:
            actions:
              - title: Acknowledge
                action: "{{ acknowledge_action_id }}"
            tag: automation.pagerduty_alert
          message: "PagerDuty: {{ trigger.json.event.data.message }}"
      - service: switch.turn_on
        target:
          entity_id: switch.party_lights
      - wait_for_trigger:
          - platform: event
            event_data:
              action: "{{ acknowledge_action_id }}"
            event_type: mobile_app_notification_action
      - service: switch.turn_off
        target:
          entity_id: switch.party_lights
      - service: notify.notify
        data:
          data:
            tag: automation.pagerduty_alert
          message: clear_notification
