---
homeassistant:
  customize:
    automation.alert_pagerduty:
      icon: mdi:alert

automation:
  - id: alert_pagerduty
    alias: Alert - PagerDuty
    trigger:
      - platform: webhook
        variables:
          acknowledge_action_id: ACK_{{ trigger.json.event.id }}
        webhook_id: !secret webhook_pagerduty_id
    condition:
      - condition: state
        entity_id: person.djhanggi
        state: home
    action:
      - service: script.send_alert
        data:
          tag: automation.alert_pagerduty
          title: PagerDuty
          message: "PagerDuty: {{ trigger.json.event.data.message }}"
          flash_lights: true
          unsilence_phone: true
          use_speakers: true
          ack_id: "{{ acknowledge_action_id }}"
          sounds: speakers
