---
homeassistant:
  customize:
    automation.alert_phone_call:
      icon: mdi:alarm-bell

automation:
  - id: alert_phone_call
    alias: Alert - Phone Call
    mode: single
    trigger:
      - entity_id: sensor.scarif_phone_state
        platform: state
        from: idle
        to: ringing
    condition:
      - entity_id: person.djhanggi
        condition: state
        state: home
    action:
      - parallel:
          - if:
              - condition: template
                value_template: >
                  {{ not is_state("sensor.scarif_ringer_mode", "normal") or
                  states("sensor.scarif_volume_level_ringer") | int < 5 }}
            then:
              - service: script.alert_send
                data:
                  tag: automation.alert_phone_call
                  message: scarif is ringing
                  devices:
                    - watch
                    - laptop
                  flash_lights: true
          - if:
              - condition: template
                value_template: >
                  {{ is_state("sensor.scarif_do_not_disturb_sensor", "off") and
                  is_state("sensor.scarif_ringer_mode", "vibrate") }}
            then:
              - service: notify.mobile_app_scarif
                data:
                  message: command_ringer_mode
                  data:
                    command: normal
              - delay:
                  seconds: 5
              - service: notify.mobile_app_scarif
                data:
                  message: command_ringer_mode
                  data:
                    command: vibrate
