# https://prettier.io/docs/en/options.html
printWidth: 80
tabWidth: 2
useTabs: false
semi: false
singleQuote: false
quoteProps: "as-needed"
trailingComma: "es5"
bracketSpacing: true
proseWrap: "always"
endOfLine: "lf"
