# https://prettier.io/docs/en/options.html
---
arrowParens: always
bracketSpacing: true
endOfLine: "lf"
printWidth: 80
proseWrap: "always"
quoteProps: "as-needed"
semi: true
singleQuote: false
tabWidth: 2
trailingComma: "es5"
useTabs: false
