---
services:
  deconz:
    image: deconzcommunity/deconz
    container_name: deconz
    restart: always
    ports: 
      - 82:82
      - 445:445
    volumes:
      - /mnt/deconz/opt/deCONZ/:/opt/deCONZ/
    devices:
      - /dev/ttyACM0
    environment:
      - DECONZ_WEB_PORT=82
      - DECONZ_WS_PORT=445
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0