---
services:
  duckdns:
    image: ghcr.io/linuxserver/duckdns
    container_name: duckdns
    network_mode: host
    options:
      max-size: 512k
    environment:
      - TZ=$TIMEZONE
      - SUBDOMAINS=$DUCKDNS_SUBDOMAIN
      - TOKEN=$DUCKDNS_TOKEN
      - LOG_FILE=true
    volumes:
      - /mnt/docker/duckdns/config/:/config/
    restart: unless-stopped
