---
services:
  duckdns:
    container_name: duckdns
    image: ghcr.io/linuxserver/duckdns
    network_mode: host
    environment:
      SUBDOMAINS: $DUCKDNS_SUBDOMAIN
      TOKEN: $DUCKDNS_TOKEN
      TZ: $TIMEZONE
    volumes:
      - /mnt/docker/duckdns/config/:/config/
    logging:
      options:
        max-size: 512k
    restart: unless-stopped
