---
services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    network_mode: host
    volumes:
      - $VOLUME_ROOT/chome/home-assistant/automations.yaml:/config/automations.yaml
      - $VOLUME_ROOT/chome/home-assistant/configuration.yaml:/config/configuration.yaml
      - $VOLUME_ROOT/chome/home-assistant/packages/:/config/packages/
      - $VOLUME_ROOT/chome/home-assistant/scenes.yaml:/config/scenes.yaml
      - $VOLUME_ROOT/chome/home-assistant/scripts.yaml:/config/scripts.yaml
      - $VOLUME_ROOT/chome/home-assistant/secrets.yaml:/config/secrets.yaml
      - $VOLUME_ROOT/docker/home-assistant/config/:/config/
    privileged: true
    logging:
      options:
        max-file: "2"
        max-size: 512m
    restart: unless-stopped
