services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    network_mode: host
    volumes:
      - ./volumes/home-assistant/config/:/config/
      - ./home-assistant/configuration.yaml:/config/configuration.yaml
      - ./home-assistant/secrets.yaml:/config/secrets.yaml
      - ./home-assistant/packages/:/config/packages/
      - ./home-assistant/automations.yaml:/config/automations.yaml
      - ./home-assistant/scenes.yaml:/config/scenes.yaml
      - ./home-assistant/scripts.yaml:/config/scripts.yaml
    restart: unless-stopped
    privileged: true
