---
services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    network_mode: host
    options:
      max-size: 512m
      max-file: 2
    volumes:
      - /mnt/docker/home-assistant/config/:/config/
      - /mnt/chome/home-assistant/configuration.yaml:/config/configuration.yaml
      - /mnt/chome/home-assistant/secrets.yaml:/config/secrets.yaml
      - /mnt/chome/home-assistant/packages/:/config/packages/
      - /mnt/chome/home-assistant/automations.yaml:/config/automations.yaml
      - /mnt/chome/home-assistant/scenes.yaml:/config/scenes.yaml
      - /mnt/chome/home-assistant/scripts.yaml:/config/scripts.yaml
    restart: unless-stopped
    privileged: true
