---
services:
  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex
    network_mode: host
    environment:
      PGID: $CHOME_GID
      PUID: $CHOME_UID
      VERSION: docker
    volumes:
      - /mnt/docker/plex/config/:/config/
      - /mnt/media/:/media/
    privileged: true
    logging:
      options:
        max-file: "2"
        max-size: 512m
    restart: unless-stopped
