---
services:
  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex
    network_mode: host
    environment:
      - PUID=$CHOME_UID
      - PGID=$CHOME_GID
      - VERSION=docker
    volumes:
      - /mnt/docker/plex/config/:/config/
      - /mnt/media/:/media/
    privileged: true
    restart: unless-stopped
