---
services:
  swag:
    container_name: swag
    image: ghcr.io/linuxserver/swag
    restart: unless-stopped
    network_mode: host
    volumes:
      - $VOLUME_ROOT/docker/swag/config/:/config/
      - type: bind
        source: $VOLUME_ROOT/chome/swag/default.conf
        target: /config/nginx/site-confs/default
        read_only: true
    environment:
      PGID: $CHOME_GID
      PUID: $CHOME_UID
      SUBDOMAINS: $SWAG_SUBDOMAINS
      TZ: $TIMEZONE
      URL: $SWAG_DOMAIN
      VALIDATION: http
    logging:
      options:
        max-file: "2"
        max-size: 512m
    cap_add:
      - NET_ADMIN
