services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    network_mode: host
    environment:
      - PUID=$CHOME_UID
      - PGID=$CHOME_GID
      - TZ=$TIMEZONE
      - URL=$SWAG_DOMAIN
      - SUBDOMAINS=$SWAG_SUBDOMAINS
      - VALIDATION=http
    volumes:
      - ./volumes/swag/config/:/config/
      - type: bind
        source: ./swag/default.conf
        target: /config/nginx/site-confs/default
        read_only: true
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
