---
services:
  swag:
    container_name: swag
    image: ghcr.io/linuxserver/swag
    network_mode: host
    environment:
      PGID: $CHOME_GID
      PUID: $CHOME_UID
      SUBDOMAINS: $SWAG_SUBDOMAINS
      TZ: $TIMEZONE
      URL: $SWAG_DOMAIN
      VALIDATION: http
    volumes:
      - /mnt/docker/swag/config/:/config/
      - read_only: true
        source: /mnt/chome/swag/default.conf
        target: /config/nginx/site-confs/default
        type: bind
    cap_add:
      - NET_ADMIN
    logging:
      options:
        max-file: "2"
        max-size: 512m
    restart: unless-stopped
