---
services:
  uptime-kuma:
    container_name: uptime-kuma
    # TODO: Update to latest once 1.18 is stable
    image: louislam/uptime-kuma:beta
    restart: always
    ports:
      - $HOST_IP:3001:3001
    volumes:
      - $VOLUME_ROOT/docker/uptime-kuma/data/:/app/data/
      - /var/run/docker.sock:/var/run/docker.sock:ro
