---
services:
  wyze-bridge:
    container_name: wyze-bridge
    image: mrlt8/wyze-bridge:latest
    network_mode: host
    environment:
      ENABLE_AUDIO: "True"
      WYZE_EMAIL: $WYZE_EMAIL
      WYZE_PASSWORD: $WYZE_PASSWORD
    logging:
      options:
        max-size: 512k
    restart: unless-stopped
