---
homeassistant:
  customize:
    automation.desk_lamp_timing:
      icon: mdi:sun-clock
    binary_sensor.desk_lamp_used_completely_today:
      icon: mdi:sun-clock

timer:
  desk_lamp_timer:
    name: Desk Lamp Timer
    duration: "00:30:00"
    icon: mdi:sun-clock

automation:
  - id: desk_lamp_timing
    alias: Desk Lamp Timing
    mode: single
    trigger:
      - id: lamp_turned_on
        entity_id: switch.desk_lamp
        platform: state
        to: "on"
      - id: lamp_turned_off
        entity_id: switch.desk_lamp
        platform: state
        to: "on"
      - id: timer_started
        platform: event
        event_type: timer.start
        event_data:
          entity_id: timer.desk_lamp_timer
      - id: timer_stopped
        platform: event
        event_type: 
          - timer.paused
          - timer.finished
          - timer.cancelled
        event_data:
          entity_id: timer.desk_lamp_timer
    condition:
      - condition: state
        entity_id: sensor.phase_of_day
        state:
          - Morning
          - Daytime
      - condition: state
        entity_id: binary_sensor.desk_lamp_used_completely_today
        state: "off"
    action:
      - choose:
        - conditions:
            - '{{ trigger.id == "lamp_turned_on" }}'
          sequence:
            - service: timer.start
              target: 
                entity_id: timer.desk_lamp_timer
        - conditions:
            - '{{ trigger.id == "lamp_turned_off" }}'
          sequence:
            - service: timer.pause
              target: 
                entity_id: timer.desk_lamp_timer
        - conditions:
            - '{{ trigger.id == "timer_started" }}'
          sequence:
            - service: switch.turn_on
              target: 
                entity_id: switch.desk_lamp
        - conditions:
            - '{{ trigger.id == "timer_ended" }}'
          sequence:
            - service: switch.turn_off
              target: 
                entity_id: switch.desk_lamp

template:
  - trigger:
    - id: reset_day
      entity_id: sensor.phase_of_day
      platform: state
      from: Sleeping
      to:
        - Morning
        - Daytime
    - id: timer_ended
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.desk_lamp_timer
    binary_sensor:
      - unique_id: desk_lamp_used_completely_today
        name: Desk Lamp Used Completely Today
        state: '{{ trigger.id == "timer_ended" or not trigger.id == "reset_day"}}'
