---
homeassistant:
  customize:
    automation.shut_off_desk_lamp:
      icon: mdi:timer
    sensor.last_desk_lamp_timestamp:
      icon: mdi:sun-clock

logbook:
  exclude:
    entities:
      - sensor.last_desk_lamp_timestamp

automation:
  - id: shut_off_desk_lamp
    alias: Shut Off Desk Lamp
    mode: single
    trigger:
      - entity_id: switch.desk_lamp
        platform: state
        to: "on"
        for:
          minutes: 30
    action:
      - service: switch.turn_off
        target:
          entity_id: switch.desk_lamp

template:
  - trigger:
      - platform: state
        entity_id: switch.desk_lamp
        to: "on"
    sensor:
      - unique_id: last_desk_lamp_timestamp
        name: Last Desk Lamp Timestamp
        state: "{{ now() | as_timestamp }}"