---
homeassistant:
  customize:
    automation.backup_home_assistant:
      icon: mdi:backup-restore

automation:
  - id: backup_home_assistant
    alias: Backup - Home Assistant
    trigger:
      - platform: time
        at: "03:05:00"
    condition:
      - condition: time
        weekday:
          - wed
          - sun
    action:
      service: backup.create
