---
homeassistant:
  customize:
    automation.server_backup_home_assistant:
      icon: mdi:backup-restore

automation:
  - id: server_backup_home_assistant
    alias: Server - Backup Home Assistant
    trigger:
      - platform: time
        at: "03:05:00"
    condition:
      - condition: time
        weekday:
          - wed
          - sun
    action:
      service: backup.create
