---
homeassistant:
  customize:
    automation.notify_on_system_change:
      icon: mdi:bell-cancel

automation:
  - id: notify_on_system_change
    alias: Notify on System Change
    mode: single
    trigger:
      - id: shutdown
        platform: homeassistant
        event: shutdown
      - id: start
        platform: homeassistant
        event: start
    action:
      - service: notify.notify
        data:
          data:
            tag: automation.notify_on_system_change
          message: clear_notification
      - service: notify.notify
        data:
          data:
            tag: automation.notify_on_system_change
          message: |
            {% if trigger.id == "shutdown" %}
              Home Assistant is shutting down
            {% elif trigger.id == "start" %}
              Home Assistant has started
            {% endif %}
