---
homeassistant:
  customize:
    automation.ups_trigger_shut_down:
      icon: mdi:battery-alert

automation:
  - id: ups_trigger_shut_down
    alias: UPS - Trigger Shut-Down
    trigger:
      - entity_id: sensor.ups_battery_charge
        platform: numeric_state
        below: 50
    action:
      - service: button.press
        target:
          entity_id: button.bespin_nas_shutdown
      - service: script.alert_send
        data:
          tag: automation.alert_ups
          message: Shutting down NAS because of UPS battery
