---
homeassistant:
  customize:
    package.node_anchors:
      harmony_dyson_fan_device: &HARMONY_DYSON_FAN_DEVICE
        device: !secret harmony_dyson_fan_device_id
    automation.dyson_fan_set_speed:
      icon: mdi:speedometer
    automation.dyson_fan_oscillate_on_start:
      icon: mdi:rotate-360

logbook:
  exclude:
    entities:
      - input_boolean.dyson_fan_power
      - input_boolean.dyson_fan_oscillating
      - input_boolean.dyson_fan_target_speed
      - script.dyson_fan_send_command
      - script.dyson_fan_toggle_power
      - script.dyson_fan_toggle_oscillate
      - script.dyson_fan_toggle_speed

input_boolean:
  dyson_fan_power:
    name: Dyson Fan - Power
    icon: mdi:fan
  dyson_fan_oscillating:
    name: Dyson Fan - Oscillating
    icon: mdi:fan

input_number:
  dyson_fan_speed:
    name: Dyson Fan - Speed
    min: 1
    max: 10
    step: 1
    icon: mdi:fan
  dyson_fan_target_speed:
    name: Dyson Fan - Target Speed
    min: 1
    max: 10
    step: 1
    icon: mdi:fan

script:
  dyson_fan_send_command:
    alias: Dyson Fan - Send Command
    description: >
      Sends a command to the Dyson Fan, particularly to manage atomicity.
    sequence:
      - service: remote.send_command
        target:
          entity_id: remote.harmony
        data:
          <<: *HARMONY_DYSON_FAN_DEVICE
          command: "{{ command }}"
    mode: single
    icon: mdi:fan
  dyson_fan_correct_power:
    alias: Dyson Fan - Correct Power
    sequence:
      - service: script.dyson_fan_send_command
        data:
          command: PowerToggle
    mode: single
    icon: mdi:fan-alert
  dyson_fan_toggle_power:
    alias: Dyson Fan - Toggle Power
    sequence:
      # Ensure that setting temperature is not currently running to guarantee
      # atomicity with that script.
      - wait_template: >
          {{ is_state("script.dyson_fan_toggle_speed", "off") }}
      - service: script.dyson_fan_send_command
        data:
          command: PowerToggle
      - service: input_boolean.toggle
        target:
          entity_id: input_boolean.dyson_fan_power
      # Delay to allow time for the AC to process the command.
      - delay:
          milliseconds: 100
    mode: queued
    icon: mdi:fan
  dyson_fan_toggle_oscillate:
    alias: Dyson Fan - Toggle Oscillate
    sequence:
      # Ensure that setting temperature is not currently running to guarantee
      # atomicity with that script.
      - wait_template: >
          {{ is_state("script.dyson_fan_toggle_speed", "off") }}
      - condition: state
        entity_id: input_boolean.dyson_fan_power
        state: "on"
      - service: script.dyson_fan_send_command
        data:
          command: Oscillate
      - service: input_boolean.toggle
        target:
          entity_id: input_boolean.dyson_fan_oscillating
      # Delay to allow time for the AC to process the command.
      - delay:
          milliseconds: 100
    mode: single
    icon: mdi:fan
  dyson_fan_toggle_speed:
    alias: Dyson Fan - Toggle Speed
    sequence:
      # Delay to allow time for any existing fan scripts to run and finish.
      - delay:
          milliseconds: 100
      # Fail if another AC command is running to guarantee atomicity.
      - condition: state
        entity_id: script.dyson_fan_send_command
        state: "off"
      - condition: state
        entity_id: input_boolean.dyson_fan_power
        state: "on"
      - service: script.dyson_fan_send_command
        data:
          command: >
            {% if increase_speed %}
              FanModeUp
            {% else %}
              FanModeDown
            {% endif %}
      - service: >
          {% if increase_speed %}
            input_number.increment
          {% else %}
            input_number.decrement
          {% endif %}
        target:
          entity_id: input_number.dyson_fan_speed
    mode: queued
    icon: mdi:fan-plus
    max: 9

automation:
  - id: dyson_fan_set_speed
    alias: Dyson Fan - Set Speed
    description: >
      Sets the fan speed to the target speed.
    trigger:
      - platform: state
        entity_id: input_boolean.dyson_fan_power
        to: "on"
      - platform: state
        entity_id: input_number.dyson_fan_target_speed
    action:
      - repeat:
          while: >
            {{ is_state("input_boolean.dyson_fan_power", "on") and
              states("input_number.dyson_fan_target_speed") | int !=
              states("input_number.dyson_fan_speed") | int }}
          sequence:
            - service: script.dyson_fan_toggle_speed
              data:
                increase_speed: >
                  {{ states("input_number.dyson_fan_speed") | int <
                  states("input_number.dyson_fan_target_speed") | int }}
    mode: restart

fan:
  - platform: template
    fans:
      dyson_fan:
        friendly_name: Dyson Fan
        unique_id: fan.dyson_fan
        value_template: >
          {{ states("input_boolean.dyson_fan_power") }}
        oscillating_template: >
          {{ is_state("input_boolean.dyson_fan_oscillating", "on") }}
        percentage_template: >
          {{ states("input_number.dyson_fan_target_speed") | int * 10 }}
        turn_on:
          - condition: state
            entity_id: input_boolean.dyson_fan_power
            state: "off"
          - service: script.dyson_fan_toggle_power
        turn_off:
          - condition: state
            entity_id: input_boolean.dyson_fan_power
            state: "on"
          - service: script.dyson_fan_toggle_power
          - service: input_boolean.turn_off
            target:
              entity_id: input_boolean.dyson_fan_oscillating
        set_oscillating:
          - condition: >
              {{ states("input_boolean.dyson_fan_oscillating") != oscillating }}
          - service: script.dyson_fan_toggle_oscillate
        set_percentage:
          - service: input_number.set_value
            target:
              entity_id: input_number.dyson_fan_target_speed
            data:
              value: "{{ percentage | int / 10 }}"
        speed_count: 10
