---
homeassistant:
  customize:
    automation.kitchen_lights_sync_power_from_wyze:
      icon: mdi:light-switch
    automation.turn_off_idle_kitchen_lights:
      icon: mdi:timer

logbook:
  exclude:
    entities:
      - input_boolean.kitchen_lights_power
      - script.set_kitchen_lights_power

ifttt:
  key:
    djhanggi_wyze_ifttt: !secret djhanggi_wyze_ifttt

input_boolean:
  kitchen_lights_power:
    name: Kitchen Lights - Power
    initial: false
    icon: mdi:light-switch

script:
  set_kitchen_lights_power:
    alias: Set Kitchen Lights Power
    description: >
      Sends command to IFTTT to turn on or off Wyze Kitchen Lights
    sequence:
      service: ifttt.trigger
      data:
        event: 'kitchen_lights_power_{{ "on" if power else "off" }}'
    icon: mdi:light-switch

automation:
  - id: kitchen_lights_sync_power_from_wyze
    alias: Kitchen Lights - Sync Power From Wyze
    trigger:
      - platform: webhook
        id: power_on
        webhook_id: !secret kitchen_lights_wyze_ifttt_webhook_sync_power_on
      - platform: webhook
        id: power_off
        webhook_id: !secret kitchen_lights_wyze_ifttt_webhook_sync_power_off
    action:
      - service: >
          {% if trigger.id == "power_on" %}
            input_boolean.turn_on
          {% elif trigger.id == "power_off" %}
            input_boolean.turn_off
          {% endif %}
        target:
          entity_id: input_boolean.kitchen_lights_power
    mode: single

switch:
  - platform: template
    switches:
      kitchen_lights:
        friendly_name: Kitchen Lights
        unique_id: kitchen_lights
        value_template: >
          {{ is_state("input_boolean.kitchen_lights_power", "on") }}
        turn_on:
          - service: script.set_kitchen_lights_power
            data:
              power: true
          - service: input_boolean.turn_on
            target:
              entity_id: input_boolean.kitchen_lights_power
        turn_off:
          - service: script.set_kitchen_lights_power
            data:
              power: false
          - service: input_boolean.turn_off
            target:
              entity_id: input_boolean.kitchen_lights_power
