---
homeassistant:
  customize:
    automation.living_room_ac_set_temperature:
      icon: mdi:thermometer
    automation.living_room_ac_correct_power_on:
      icon: mdi:thermometer-check
    switch.living_room_ac:
      icon: mdi:air-conditioner
      friendly_name: Living Room AC - Switch

logbook:
  exclude:
    entities:
      - script.living_room_ac_send_command
      - script.living_room_ac_toggle_power
      - script.living_room_ac_toggle_temperature
      - switch.living_room_ac

input_boolean:
  living_room_ac_power:
    name: Living Room AC - Power
    icon: mdi:air-conditioner

input_number:
  living_room_ac_temperature:
    name: Living Room AC - Temperature
    min: 60.0
    max: 90.0
    step: 1.0
    icon: mdi:thermometer

input_select:
  living_room_ac_mode:
    name: Living Room AC - Mode
    options:
      - Cool
      - Money Saver
      - Fan Only
    icon: mdi:air-conditioner

script:
  living_room_ac_send_command:
    alias: Living Room AC - Send Commmand
    description: |
      Sends a command to the Living Room AC, particularly to manage atomicity.
      Options include
        * PowerToggle
        * TempHotter
        * TempCooler
        * CoolMode
        * MoneySaverMode
        * FanMode
        * FanModeUp
    sequence:
      - service: remote.send_command
        target:
          entity_id: remote.harmony
        data:
          device: !secret harmony_friedrich_ac_device_id
          command: "{{ command }}"
    mode: single
    icon: mdi:air-conditioner
  living_room_ac_correct_power:
    alias: Living Room AC - Correct Power
    sequence:
      - service: script.living_room_ac_send_command
        data:
          command: PowerToggle
      - service: automation.trigger
        target:
          entity_id: automation.living_room_ac_set_mode
    mode: single
    icon: mdi:power
  living_room_ac_set_mode:
    alias: Living Room AC - Set Mode
    sequence:
      - service: script.living_room_ac_send_command
        data:
          command: >
            {% set MODES = {
              "Cool": "CoolMode",
              "Money Saver": "MoneySaverMode",
              "Fan Only": "FanMode",
            } %} {% set mode_command =
              MODES[states("input_select.living_room_ac_mode")] |
              default("Cool") %}
            {{ mode_command }}
    mode: single
    icon: mdi:air-conditioner
  living_room_ac_toggle_power:
    alias: Living Room AC - Toggle Power
    sequence:
      # Ensure that setting temperature is not currently running to guarantee
      # atomicity with that script.
      - wait_template: >
          {{ is_state("script.living_room_ac_toggle_temperature", "off") }}
      - service: script.living_room_ac_send_command
        data:
          command: PowerToggle
      - service: input_boolean.toggle
        target:
          entity_id: input_boolean.living_room_ac_power
      # Delay to allow time for the AC to process the command.
      - delay:
          milliseconds: 750
    mode: queued
    icon: mdi:air-conditioner
  living_room_ac_toggle_temperature:
    alias: Living Room AC - Toggle Temperature
    sequence:
      # Delay to allow time for any existing AC scripts to run and finish.
      - delay:
          milliseconds: 750
      # Fail if another AC command is running to guarantee atomicity.
      - condition: state
        entity_id: script.living_room_ac_send_command
        state: "off"
      - condition: state
        entity_id: input_boolean.living_room_ac_power
        state: "on"
      - service: script.living_room_ac_send_command
        data:
          command: >
            {% if increase_temperature %}
              TempHotter
            {% else %}
              TempCooler
            {% endif %}
      - service: >
          {% if increase_temperature %}
            input_number.increment
          {% else %}
            input_number.decrement
          {% endif %}
        target:
          entity_id: input_number.living_room_ac_temperature
    mode: single
    icon: mdi:thermometer

automation:
  - id: living_room_ac_set_temperature
    alias: Living Room AC - Set Temperature
    description: >
      Sets the AC temperature to the set point of climate.living_room_ac.
    trigger:
      - platform: state
        entity_id: climate.living_room_ac
        attribute: temperature
      - platform: state
        entity_id: input_boolean.living_room_ac_power
        to: "on"
    mode: single
    action:
      - repeat:
          while: >
            {{ is_state("input_boolean.living_room_ac_power", "on") and
              states("input_number.living_room_ac_temperature") | int !=
              state_attr("climate.living_room_ac", "temperature") | int }}
          sequence:
            - service: script.living_room_ac_toggle_temperature
              data:
                increase_temperature: >
                  {{ states("input_number.living_room_ac_temperature") | int <
                  state_attr("climate.living_room_ac", "temperature") | int }}

switch:
  - platform: template
    switches:
      living_room_ac:
        value_template: >
          {{ is_state("input_boolean.living_room_ac_power", "on") }}
        turn_on:
          - condition: state
            entity_id: input_boolean.living_room_ac_power
            state: "off"
          - service: script.living_room_ac_toggle_power
        turn_off:
          - condition: state
            entity_id: input_boolean.living_room_ac_power
            state: "on"
          - service: script.living_room_ac_toggle_power

climate:
  - platform: generic_thermostat
    unique_id: living_room_ac
    name: Living Room AC
    heater: switch.living_room_ac
    target_sensor: sensor.living_room_sonoff_temperature
    min_temp: 60
    max_temp: 90
    ac_mode: true
    cold_tolerance: 1.0
    hot_tolerance: 1.0
    min_cycle_duration:
      minutes: 2
    initial_hvac_mode: "off"
    precision: 1.0
