default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies: !secret trusted_proxies

homeassistant:
  external_url: !secret external_url
  packages: !include_dir_named packages/

automation manual: !include_dir_merge_list configurations/automations/
