default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies: !secret trusted_proxies

homeassistant: !secret homeassistant

automation: !include configurations/automations.yaml
script: !include configurations/scripts.yaml
scene: !include configurations/scenes.yaml
