---
homeassistant:
  name: !secret homeassistant_name
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: imperial
  external_url: !secret homeassistant_external_url
  packages: !include_dir_named packages/

http:
  use_x_forwarded_for: true
  trusted_proxies: !secret http_trusted_proxies

automation: !include automations.yaml
backup:
config:
conversation:
counter:
frontend:
history:
input_boolean:
input_button:
input_datetime:
input_number:
input_select:
input_text:
logbook:
logger:
  default: debug
map:
media_source:
mobile_app:
my:
person:
scene: !include scenes.yaml
script: !include scripts.yaml
stream:
sun:
system_health:
timer:
webhook:
zeroconf:
