---
homeassistant:
  customize:
    automation.morning:
      icon: mdi:weather-sunny
    automation.daytime:
      icon: mdi:weather-sunny
    automation.evening:
      icon: mdi:weather-sunset

input_boolean:
  open_blinds_in_morning:
    name: Open Blinds in Morning
    icon: mdi:blinds-open

automation:
  - id: morning
    alias: Morning
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.phase_of_day
        from: Sleeping
        to: Morning
    condition:
      - entity_id: person.djhanggi
        condition: state
        state: home
    action:
      - scene: scene.morning
      - if:
          - '{{ is_state("input_boolean.open_blinds_in_morning", "on") }}'
        then:
          - scene: scene.ajar_blinds
      - service: script.spotify_meditate
        data:
          media_player_id: media_player.bedroom_speaker
  - id: daytime
    alias: Daytime
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.phase_of_day
        from: Morning
        to: Daytime
    condition:
      - entity_id: person.djhanggi
        condition: state
        state: home
    action:
      - scene: scene.daytime
  - id: evening
    alias: Evening
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.phase_of_day
        from: Daytime
        to: Evening
    condition:
      - entity_id: person.djhanggi
        condition: state
        state: home
    action:
      - service: homeassistant.turn_off
        target:
          entity_id: group.lighting
      - scene: scene.evening
      - scene: scene.closed_blinds

scene:
  - id: morning
    name: Morning
    icon: mdi:weather-sunset-up
    entities:
      light.bed:
        state: "on"
      light.bedroom_lamp:
        state: "on"
      light.ceiling_e:
        state: "on"
      light.hallway_e:
        state: "on"
      switch.adaptive_lighting_all_light_bulbs:
        state: "on"
      switch.adaptive_lighting_sleep_mode_all_light_bulbs:
        state: "off"
      switch.monitor:
        state: "on"
      switch.sunlight_lamp:
        state: "on"
      media_player.bedroom_speaker:
        state: "idle"
        volume_level: 0.45
  - id: daytime
    name: Daytime
    icon: mdi:weather-sunny
    entities:
      input_boolean.is_sleeping:
        state: "off"
      fan.dyson_fan:
        state: "on"
        oscillating: true
      fan.dyson_heater_fan:
        state: "off"
      light.bed:
        state: "off"
      light.bedroom_lamp:
        state: "on"
      light.ceiling_e:
        state: "on"
      light.ceiling_w:
        state: "on"
      light.living_room_lamp:
        state: "on"
      switch.adaptive_lighting_all_light_bulbs:
        state: "on"
      switch.adaptive_lighting_sleep_mode_all_light_bulbs:
        state: "off"
      switch.monitor:
        state: "on"
      switch.sunlight_lamp:
        state: "off"
  - id: evening
    name: Evening
    icon: mdi:weather-sunset
    entities:
      light.bed:
        state: "on"
      light.bedroom_lamp:
        state: "off"
      light.bookshelf:
        state: "on"
      light.ceiling_lights:
        state: "off"
      light.hallway_lights:
        state: "off"
      light.living_room_lamp:
        state: "on"
      switch.adaptive_lighting_sleep_mode_all_light_bulbs:
        state: "on"
      switch.monitor:
        state: "off"
      switch.sunlight_lamp:
        state: "off"
      fan.dyson_heater_fan:
        state: "on"
        oscillating: true
      humidifier.levoit_humidifier:
        state: "on"
        humidity: 50
