---
homeassistant:
  customize:
    automation.plant_care:
      icon: mdi:flower
    switch.bedroom_plant_light:
      icon: mdi:flower
      device_class: light
    switch.living_room_plant_light:
      icon: mdi:flower
      device_class: light

automation:
  - id: plant_care
    alias: Plant Care
    description: Turns on/off plant care entities (lights, etc.).
    mode: queued
    trigger:
      - id: plant_sunrise
        entity_id: sensor.phase_of_day
        platform: state
        to:
          - Morning
          - Daytime
      - id: plant_sunset
        entity_id: sensor.phase_of_day
        platform: state
        from: Daytime
        to: Evening
    action:
      - service: |
          {% if trigger.id == "plant_sunrise" %}
            switch.turn_on
          {% elif trigger.id == "plant_sunset" %}
            switch.turn_off
          {% else %}
            switch.toggle
          {% endif %}
        target:
          entity_id:
            - switch.bedroom_plant_light
            - switch.living_room_plant_light
