---
homeassistant:
  customize:
    automation.play_headspace:
      icon: mdi:yoga

input_datetime:
  headspace_time:
    name: Headspace Time
    icon: mdi:weather-sunset-up
    has_time: true
    initial: "6:05:00"

automation:
  - id: play_headspace
    alias: Play Headspace
    mode: single
    trigger:
      - id: reset_headspace_time
        entity_id: sensor.phase_of_day
        platform: state
        from: Sleeping
        to:
          - Morning
          - Daytime
      - id: headspace_time
        platform: time
        at: input_datetime.headspace_time
    action:
      - choose:
          - conditions: '{{ trigger.id == "reset_headspace_time" }}'
            sequence:
              - service: input_datetime.set_datetime
                data:
                  time: "6:05:00"
                target:
                  entity_id: input_datetime.headspace_time
              - stop:
          - conditions: '{{ trigger.id == "headspace_time" }}'
            sequence:
              - condition: or
                conditions:
                  - entity_id: person.djhanggi
                    condition: state
                    state: not_home
                  - entity_id: calendar.daniel_hanggi_braze_com
                    condition: state
                    state: "on"
                  - entity_id: sensor.phase_of_day
                    condition: state
                    state:
                      - Morning
                      - Sleeping
              - stop:
      - wait_template:
          '{{ is_state("binary_sensor.scarif_device_locked", "off") }}'
      - service: notify.mobile_app_scarif
        data:
          title: Headspace
          message: Headspace
          data:
            ttl: 3600
            timeout: 3
