---
homeassistant:
  customize:
    automation.play_peloton_class:
      icon: mdi:yoga

input_datetime:
  peloton_time:
    name: Peloton Time
    icon: mdi:weather-sunset-up
    has_time: true
    initial: "12:00:30"

script:
  play_peloton_class:
    alias: Play Peloton Class
    icon: mdi:yoga
    mode: single
    sequence:
      - service: script.tv_turn_on
      - service: androidtv.adb_command
        data:
          command: RESUME
        target:
          entity_id: media_player.android_tv_hoth
      - delay:
          seconds: 1
      - service: androidtv.adb_command
        data:
          command: am force-stop com.onepeloton.callisto
        target:
          entity_id: media_player.android_tv_hoth
      - delay:
          seconds: 1
      - service: androidtv.adb_command
        data:
          command: >
            am start -a android.intent.action.VIEW -d -n
            com.onepeloton.callisto/.MainActivity
        target:
          entity_id: media_player.android_tv_hoth
      - delay:
          seconds: 10
      - repeat:
          sequence:
            - service: androidtv.adb_command
              data:
                command: "{{ repeat.item }}"
              target:
                entity_id: media_player.android_tv_hoth
            - delay:
                milliseconds: 750
          for_each:
            # Navigate to Classes
            - LEFT
            - DOWN
            - CENTER
            # Navigate to Yoga
            - RIGHT
            - CENTER
            # Navigate to Filters
            - UP
            - RIGHT
            - CENTER
            # Navigate to Length
            - DOWN
            - CENTER
            # Select 5- and 10-minute classes
            - CENTER
            - DOWN
            - CENTER
            - BACK
            # Filter by Not Taken
            - DOWN
            - DOWN
            - DOWN
            - DOWN
            - DOWN
            - DOWN
            - DOWN
            - DOWN
            - DOWN
            - CENTER
            # Go back to class page
            - BACK
            # Select first class
            - CENTER
            # Play first class
            - CENTER

automation:
  - id: play_peloton_class
    alias: Play Peloton Class
    mode: single
    trigger:
      - id: reset_peloton_time
        entity_id: sensor.phase_of_day
        platform: state
        from: Sleeping
        to:
          - Morning
          - Daytime
      - id: peloton_time
        platform: time
        at: input_datetime.peloton_time
      - id: evening
        entity_id: sensor.phase_of_day
        platform: state
        from: Daytime
        to: Evening
    action:
      - choose:
          - conditions: '{{ trigger.id == "reset_peloton_time" }}'
            sequence:
              - service: input_datetime.set_datetime
                data:
                  time: "12:00:30"
                target:
                  entity_id: input_datetime.peloton_time
              - stop:
          - conditions:
              '{{ trigger.id == "peloton_time" or trigger.id == "evening" }}'
            sequence:
              - condition: or
                conditions:
                  - entity_id: person.djhanggi
                    condition: state
                    state: not_home
                  - entity_id: calendar.daniel_hanggi_braze_com
                    condition: state
                    state: "on"
                  - entity_id: sensor.phase_of_day
                    condition: state
                    state:
                      - Morning
                      - Sleeping
                  - condition: template
                    value_template: |
                      {% set last_midnight = now().replace(hour=0, minute=0, second=0) | as_timestamp %}
                      {% set last_peloton = state_attr("script.play_peloton_class",
                      "last_triggered") | as_timestamp %} 
                      {{ last_midnight < last_peloton }}
              - stop:
      - service: script.turn_on
        target:
          entity_id: script.play_peloton_class
