---
homeassistant:
  customize:
    automation.play_peloton_class:
      icon: mdi:yoga

input_datetime:
  peloton_time:
    name: Peloton Time
    icon: mdi:weather-sunset-up
    has_time: true
    initial: "12:00:30"

script:
  play_peloton_class:
    alias: Play Peloton Class
    icon: mdi:yoga
    mode: single
    sequence:
      - service: script.tv_turn_on
      - service: androidtv.adb_command
        data:
          command: RESUME
        target:
          entity_id: media_player.android_tv_hoth
      - delay:
          seconds: 1
      - service: androidtv.adb_command
        data:
          command: am force-stop com.onepeloton.callisto
        target:
          entity_id: media_player.android_tv_hoth
      - delay:
          seconds: 1
      - service: androidtv.adb_command
        data:
          command: >
            am start -a android.intent.action.VIEW -d -n
            com.onepeloton.callisto/.MainActivity
        target:
          entity_id: media_player.android_tv_hoth
      - delay:
          seconds: 10
      - repeat:
          sequence:
            - service: androidtv.adb_command
              data:
                command: "{{ repeat.item }}"
              target:
                entity_id: media_player.android_tv_hoth
            - delay:
                milliseconds: 750
          for_each:
            # Navigate to Classes
            - LEFT
            - DOWN
            - CENTER
            # Navigate to Yoga
            - RIGHT
            - CENTER
      - repeat:
          sequence:
            - service: androidtv.adb_command
              data:
                command: "{{ repeat.item }}"
              target:
                entity_id: media_player.android_tv_hoth
            - delay:
                milliseconds: 250
          for_each:
            # Navigate to Filters
            - UP
            - RIGHT
            - CENTER
            # Navigate to Length
            - DOWN
            - CENTER
            # Filter by 10-minute classes
            - DOWN
            - CENTER
            - BACK
            # Navigate to Type
            - DOWN
            - DOWN
            - CENTER
            # Filter by Flow classes
            - CENTER
            - BACK
            # Filter by Not Taken
            - DOWN
            - DOWN
            - DOWN
            - DOWN
            - DOWN
            - DOWN
            - DOWN
            - CENTER
      - repeat:
          sequence:
            - service: androidtv.adb_command
              data:
                command: "{{ repeat.item }}"
              target:
                entity_id: media_player.android_tv_hoth
            - delay:
                milliseconds: 750
          for_each:
            # Go back to class page
            - BACK
            # Go down, select, and play third or so class (in case a live one is running)
            - DOWN
            - CENTER
            - CENTER

automation:
  - id: play_peloton_class
    alias: Play Peloton Class
    mode: restart
    trigger:
      - id: reset_peloton_time
        entity_id: sensor.phase_of_day
        platform: state
        from: Sleeping
        to:
          - Morning
          - Daytime
      - id: peloton_time
        platform: time
        at: input_datetime.peloton_time
      - id: evening
        entity_id: sensor.phase_of_day
        platform: state
        from: Daytime
        to: Evening
    action:
      - if: '{{ trigger.id == "reset_peloton_time" }}'
        then:
          - service: input_datetime.set_datetime
            data:
              time: "12:00:30"
            target:
              entity_id: input_datetime.peloton_time
          - stop:
      - service: script.schedule_script
        data:
          script: script.play_peloton_class
          bypass_calendar: '{{ trigger.id == "evening" }}'
          window_minutes: 14
