---
homeassistant:
  customize:
    automation.spotify_management:
      icon: mdi:spotify

automation:
  - id: spotify_management
    alias: Spotify Management
    trigger:
      - id: long_running
        platform: template
        for:
          hours: 1
        value_template: >
          {{ is_state("media_player.spotify_djhanggi", "playing") and not
          is_state_attr("media_player.spotify_djhanggi", "source", "scarif") }}
      - id: away
        entity_id: person.djhanggi
        platform: state
        to: not_home
      - id: tv
        entity_id: remote.harmony
        platform: state
        to: "on"
    condition:
      - condition: not
        conditions:
          - entity_id: media_player.spotify_djhanggi
            condition: state
            state: scarif
            attribute: source
    action:
      - service: media_player.media_pause
        target:
          entity_id: media_player.spotify_djhanggi
