---
homeassistant:
  customize:
    automation.spotify_management:
      icon: mdi:spotify

automation:
  - id: spotify_management
    alias: Spotify Management
    trigger:
      - id: long_running
        platform: template
        for:
          hours: 1
        value_template: >
          {{ is_state("media_player.spotify_djhanggi", "playing") and not
          is_state_attr("media_player.spotify_djhanggi", "source", "scarif") }}
      - id: away
        entity_id: person.djhanggi
        platform: state
        to: not_home
      - id: hoth
        entity_id: media_player.cast_hoth
        platform: state
        to: "playing"
    action:
      - variables:
          source: '{{ state_attr("media_player.spotify_djhanggi", "source")}}'
      - if:
          - condition: or
            conditions:
              - '{{ trigger.id == "away" and source != "scarif" }}'
              - '{{ trigger.id == "hoth" and source != "Hoth" }}'
        then:
          - service: media_player.media_pause
            target:
              entity_id: media_player.spotify_djhanggi
