---
homeassistant:
  customize:
    automation.bedroom_button:
      icon: mdi:bed-single

automation:
  - id: bedroom_button
    alias: Bedroom Button
    mode: queued
    trigger:
      - platform: event
        event_type: deconz_event
        variables:
          device: "{{ trigger.event.data.id }}"
          event_time: "{{ trigger.event.time_fired | as_timestamp }}"
          press_type: |
            {% if trigger.event.data.event == 1002 %}
              single_press
            {% elif trigger.event.data.event == 1004 %}
              double_press
            {% elif trigger.event.data.event == 1001 %}
              long_press
            {% endif %}
    action:
      - condition: '{{ device == "aqara_bedroom_switch" }}'
      - choose:
          - conditions: '{{ press_type == "single_press" }}'
            sequence:
              - service: script.go_to_sleep
          - conditions: '{{ press_type == "double_press" }}'
            sequence:
              - variables:
                  curtain_position:
                    '{{state_attr("cover.smart_roller_shade_curtain",  "current_position")
                    }}'
              - if: "{{ curtain_position != 0 }}"
                then:
                  - scene: scene.closed_blinds
                else:
                  - scene: scene.open_blinds
          - conditions: '{{ press_type == "long_press" }}'
            sequence:
              - wait_for_trigger:
                  - platform: event
                    event_type: deconz_event
              - variables:
                  long_press_end_time:
                    "{{ wait.trigger.event.time_fired | as_timestamp }}"
              - service: script.snooze_morning_start_time
                data:
                  minutes: |
                    {% set press_duration_seconds = (long_press_end_time - event_time) | int %} 
                    {{ 15 * press_duration_seconds }}
