---
homeassistant:
  customize:
    automation.bedroom_button:
      icon: mdi:bed-single

automation:
  - id: bedroom_button
    alias: Bedroom Button
    mode: single
    trigger:
      - platform: event
        event_type: deconz_event
        variables:
          press_type: |
            {% if trigger.event.data.event == 1002 %}
              single_press
            {% elif trigger.event.data.event == 1004 %}
              double_press
            {% elif trigger.event.data.event == 1001 %}
              long_press
            {% elif trigger.event.data.event == 1003 %}
              long_press_end
            {% endif %}
    action:
      - service: homeassistant.turn_on
        target:
          entity_id: |
            {% if press_type == "single_press" %}
              script.go_to_sleep
            {% elif press_type == "double_press" %}
              {% 
                set curtain_position = 
                  state_attr("cover.smart_roller_shade_curtain", 
                    "current_position")
              %}
              {% if curtain_position != 0 %}
                scene.closed_blinds
              {% else %}
                scene.open_blinds
              {% endif %}
            {% elif press_type == "long_press" %}
              script.snooze_morning_start_time
            {% endif %}
