---
homeassistant:
  customize:
    automation.ios_sleep:
      icon: mdi:sleep
    automation.ios_snooze:
      icon: mdi:alarm-snooze
    automation.ios_meditate:
      icon: mdi:meditation

automation:
  - id: ios_sleep
    alias: iOS - Sleep
    trigger:
      platform: event
      event_data:
        actionName: iOS Sleep
      event_type: ios.action_fired
    action:
      - service: script.go_to_sleep
  - id: ios_snooze
    alias: iOS - Snooze
    trigger:
      platform: event
      event_data:
        actionName: iOS Snooze
      event_type: ios.action_fired
    action:
      - service: script.snooze_morning_start_time
  - id: ios_meditate
    alias: iOS - Meditate
    trigger:
      platform: event
      event_data:
        actionName: iOS Meditate
      event_type: ios.action_fired
    action:
      - service: script.spotify_meditate

ios:
  actions:
    - name: iOS Sleep
      icon:
        icon: mdi:sleep
        color: "#000000"
      background_color: "#ffffff"
      label:
        color: "#000000"
        text: Sleep
    - name: iOS Snooze
      icon:
        icon: mdi:alarm-snooze
        color: "#000000"
      background_color: "#ffffff"
      label:
        color: "#000000"
        text: Snooze
    - name: iOS Meditate
      icon:
        icon: mdi:meditation
        color: "#000000"
      background_color: "#ffffff"
      label:
        color: "#000000"
        text: Meditate
