---
homeassistant:
  customize:
    automation.ios_actions:
      icon: mdi:apple-ios

automation:
  - id: ios_actions
    alias: iOS - Actions
    mode: queued
    trigger:
      - platform: event
        event_type: ios.action_fired
    action:
      - variables:
          action: "{{ trigger.event.data.actionName }}"
      - choose:
          - conditions: '{{ action == "ios_find_scarif" }}'
            sequence:
              - service: script.find_scarif
          - conditions: '{{ action == "ios_spotify_meditate" }}'
            sequence:
              - service: script.spotify_meditate
                data:
                  media_player_id: media_player.bedroom_speaker
          - conditions: '{{ action == "ios_go_to_sleep" }}'
            sequence:
              - service: script.go_to_sleep
          - conditions: '{{ action == "ios_snooze_morning_start_time" }}'
            sequence:
              - service: script.snooze_morning_start_time
        default:
          - error: true
            stop: "Unrecognized iOS action: {{ action }}"

ios:
  actions:
    - name: ios_find_scarif
      icon:
        icon: mdi:phone-alert
        color: "#000000"
      background_color: "#ffffff"
      label:
        color: "#000000"
        text: Find Scarif
    - name: ios_spotify_meditate
      icon:
        icon: mdi:meditation
        color: "#000000"
      background_color: "#ffffff"
      label:
        color: "#000000"
        text: Meditate
    - name: ios_go_to_sleep
      icon:
        icon: mdi:sleep
        color: "#000000"
      background_color: "#ffffff"
      label:
        color: "#000000"
        text: Sleep
    - name: ios_snooze_morning_start_time
      icon:
        icon: mdi:alarm-snooze
        color: "#000000"
      background_color: "#ffffff"
      label:
        color: "#000000"
        text: Snooze
