---
homeassistant:
  customize:
    automation.laptop_camera_in_use:
      icon: mdi:minus-circle

logbook:
  exclude:
    entities:
      - sensor.bzusc02ff0h3md6v_frontmost_app

automation:
  - id: laptop_camera_in_use
    alias: Laptop - Camera in Use
    trigger:
      - entity_id: binary_sensor.bzusc02ff0h3md6v_camera_in_use
        platform: state
        to: "on"
    condition:
      - entity_id: sensor.scarif_do_not_disturb_sensor
        condition: state
        state: "off"
    action:
      - service: notify.mobile_app_scarif
        data:
          data:
            command: priority_only
          message: command_dnd
      - wait_for_trigger:
          - entity_id: binary_sensor.bzusc02ff0h3md6v_camera_in_use
            platform: state
            from: "on"
      - service: notify.mobile_app_scarif
        data:
          data:
            command: "off"
          message: command_dnd
