---
homeassistant:
  customize:
    automation.laptop_camera_in_use_set_dnd:
      icon: mdi:minus-circle
automation:
  - id: laptop_camera_in_use_set_dnd
    alias: Laptop Camera in Use - Set DND
    trigger:
      - entity_id: binary_sensor.bzusc02ff0h3md6v_camera_in_use
        platform: state
        to: "on"
    condition:
      - entity_id: sensor.scarif_do_not_disturb_sensor
        condition: state
        state: "off"
    action:
      - service: notify.mobile_app_scarif
        data:
          data:
            command: priority_only
          message: command_dnd
      - wait_for_trigger:
          - entity_id: binary_sensor.bzusc02ff0h3md6v_camera_in_use
            platform: state
            from: "on"
      - service: notify.mobile_app_scarif
        data:
          data:
            command: "off"
          message: command_dnd
