---
homeassistant:
  customize:
    automation.set_morning_start_time_to_sunrise:
      icon: mdi:weather-sunset-up

input_datetime:
  next_alarm_time:
    name: Next Alarm Time
    has_time: true
    icon: mdi:alarm-check

script:
  sync_next_alarm_time:
    alias: Sync Next Alarm Time from Scarif
    sequence:
      - service: input_datetime.set_datetime
        target:
          entity_id: input_datetime.next_alarm_time
        data:
          time: >
            {{
              as_timestamp(states.sensor.scarif_next_alarm.state)
              | timestamp_custom("%H:%M:%S")
              | default("00:00:00", True)
            }}
    icon: mdi:phone-clock
  set_alarm_on_scarif:
    alias: Set Alarm On Scarif
    sequence:
      - service: notify.mobile_app_scarif
        data:
          title: Set Alarm
          message: >
            {{ state_attr("input_datetime.next_alarm_time", "timestamp") |
            timestamp_custom("%H:%M", False) }}
          data:
            channel: Set Alarm
            timeout: 1
    icon: mdi:alarm-bell
  