---
homeassistant:
  customize:
    automation.backup_home_assistant:
      icon: mdi:backup-restore

automation:
  - id: backup_home_assistant
    alias: Backup Home Assistant
    trigger:
      - platform: homeassistant
        event: shutdown
        id: home_assistant_shutdown
      - platform: time
        at: "03:00:00"
    condition:
      - or:
          - '{{ trigger.id == "home_assistant_shutdown" }}'
          - condition: time
            weekday:
              - mon
              - thu
    action:
      service: backup.create
