---
homeassistant:
  customize:
    automation.turn_off_idle_bathroom_lights:
      icon: mdi:lightbulb-auto

automation:
  - id: turn_off_idle_bathroom_lights
    alias: Turn Off Idle Bathroom Lights
    mode: single
    trigger:
      - entity_id: binary_sensor.aqara_motion_bathroom
        platform: state
        for:
          minutes: 5
        from: "on"
    action:
      - service: light.turn_off
        target:
          entity_id: light.bathroom_lights
