---
scene:
  - id: chome_cool_climate
    name: CHOME Cool Climate
    entities:
      climate.living_room_ac:
        state: cool
      climate.bedroom_ac:
        state: cool
      fan.dyson_fan:
        state: "on"
        oscillating: true
      fan.dyson_heater_fan:
        state: "on"
        oscillating: true
    icon: mdi:home-thermometer

automation:
  - id: dyson_fan_oscillate_on_start
    alias: Dyson Fan - Oscillate On Start
    trigger:
      - platform: state
        entity_id: fan.dyson_fan
        from: "off"
        to: "on"
    action:
      - service: fan.oscillate
        target:
          entity_id: fan.dyson_fan
        data:
          oscillating: true
    mode: single
  - id: dyson_heater_fan_oscillate_on_start
    alias: Dyson Heater Fan - Oscillate On Start
    trigger:
      - platform: state
        entity_id: fan.dyson_heater_fan
        from: "off"
        to: "on"
    action:
      - service: fan.oscillate
        target:
          entity_id: fan.dyson_heater_fan
        data:
          oscillating: true
    mode: single
