---
scene:
  - id: chome_cool_climate
    name: CHOME Cool Climate
    entities:
      climate.living_room_ac:
        state: cool
        temperature: 67
      climate.bedroom_ac:
        state: cool
        temperature: 67
      fan.dyson_fan:
        state: "on"
        oscillating: true
      fan.dyson_heater_fan:
        state: "on"
        oscillating: true
    icon: mdi:home-thermometer
  - id: bedroom_cool_climate
    name: Bedroom Cool Climate
    entities:
      climate.bedroom_ac:
        state: cool
        temperature: 67
      fan.dyson_heater_fan:
        state: "on"
        oscillating: true
    icon: mdi:home-thermometer

automation:
  - id: cycle_ac_change_intervals
    alias: Cycle AC - Change Intervals
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.daytime_hours
    action:
      - if:
          - condition: state
            entity_id: sensor.daytime_hours
            state: "True"
        then:
          - service: scene.apply
            data:
              entities:
                input_number.cycle_ac_shutoff_timer_duration:
                  state: "30.0"
                input_number.cycle_ac_restart_timer_duration:
                  state: "30.0"
        else:
          - service: scene.apply
            data:
              entities:
                input_number.cycle_ac_shutoff_timer_duration:
                  state: "10.0"
                input_number.cycle_ac_restart_timer_duration:
                  state: "50.0"
