---
homeassistant:
  customize:
    automation.update_device_tracker_djhanggi_sensor_2:
      icon: mdi:home-map-marker

template:
  - binary_sensor:
      - unique_id: djhanggi_at_home
        name: DJHANGGI at Home
        state: >
          {{ is_state("sensor.scarif_wifi_connection", "CHOME.NYC") or
          is_state("sensor.scarif_wifi_connection", "CHOME") or
          is_state("device_tracker.scarif", "home") }}
        icon: mdi:home-map-marker

automation:
  - id: update_device_tracker_djhanggi_sensor_2
    alias: Update device_tracker.djhanggi_sensor
    mode: single
    trigger:
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: binary_sensor.djhanggi_at_home
    action:
      - service: device_tracker.see
        data:
          dev_id: "djhanggi_sensor"
          location_name: >
            {{ "home" if is_state("binary_sensor.djhanggi_at_home", "on") else
            "not_home" }}
