---
scene:
  - id: fans_on
    name: Fans On
    entities:
      fan.dyson_fan:
        state: "on"
      fan.dyson_heater_fan:
        state: "on"
    icon: mdi:home-thermometer

automation:
  - id: dyson_fan_oscillate_on_start
    alias: Dyson Fan - Oscillate On Start
    trigger:
      - platform: state
        entity_id: fan.dyson_fan
        from: "off"
        to: "on"
    action:
      - service: fan.oscillate
        target:
          entity_id: fan.dyson_fan
        data:
          oscillating: true
    mode: single
  - id: dyson_heater_fan_oscillate_on_start
    alias: Dyson Heater Fan - Oscillate On Start
    trigger:
      - platform: state
        entity_id: fan.dyson_heater_fan
        from: "off"
        to: "on"
    action:
      - service: fan.oscillate
        target:
          entity_id: fan.dyson_heater_fan
        data:
          oscillating: true
    mode: single
