---
homeassistant:
  customize:
    automation.turn_off_idle_kitchen_lights:
      icon: mdi:lightbulb-auto

automation:
  - id: turn_off_idle_kitchen_lights
    alias: Turn Off Idle Kitchen Lights
    mode: single
    trigger:
      - entity_id: binary_sensor.aqara_motion_kitchen
        platform: state
        for:
          minutes: 5
        from: "on"
    action:
      - service: switch.turn_off
        target:
          entity_id: switch.kitchen_lights
