---
homeassistant:
  customize:
    switch.kitchen_lights:
      icon: mdi:light-switch
    switch.sunlight_lamp:
      icon: mdi:weather-sunny

logbook:
  exclude:
    entities:
      - group.lighting
      - light.all_light_bulbs
      - light.ceiling_lights
      - light.hallway_lights
      - light.bathroom_lights

adaptive_lighting:
  - name: All Light Bulbs
    lights:
      - light.all_light_bulbs

group:
  lighting:
    name: Lighting
    entities:
      - switch.adaptive_lighting_all_light_bulbs
      - light.all_light_bulbs
      - switch.kitchen_lights
      - switch.sunlight_lamp

light:
  - platform: group
    name: All Light Bulbs
    unique_id: all_light_bulbs
    entities:
      - light.ceiling_e
      - light.ceiling_w
      - light.living_room_lamp
      - light.bookshelf
      - light.hallway_e
      - light.hallway_w
      - light.bathroom_e
      - light.bathroom_w
      - light.bedroom_lamp
      - light.bed
  - platform: group
    name: Ceiling Lights
    unique_id: ceiling_lights
    entities:
      - light.ceiling_e
      - light.ceiling_w
  - platform: group
    name: Hallway Lights
    unique_id: hallway_lights
    entities:
      - light.hallway_e
      - light.hallway_w
  - platform: group
    name: Bathroom Lights
    unique_id: bathroom_lights
    entities:
      - light.bathroom_e
      - light.bathroom_w

# Add input_number for the length of time
# automation:
#   - id: turn_off_idle_kitchen_lights
#     alias: Turn Off Idle Kitchen Lights
#     trigger:
#       - platform: state
#         entity_id: switch.kitchen_lights
#         to: "on"
#         for:
#           minutes: 15
#     action:
#       - service: switch.turn_off
#         target:
#           entity_id: switch.kitchen_lights
#     mode: single
# Get list of entity_ids of lights that are on:
# entity_ids:
#   {% set idle_lights = ["light.ceiling_e", "light.bookshelf"] %}
#   {{ states.light | selectattr('state','eq','on') |
#   selectattr('last_updated','lt',now() - timedelta(hours=0)) |
#   map(attribute='entity_id') | select("in", idle_lights) | list}}

# Expand all lights in a group to capture individually in scene:
# {{expand(state_attr('light.woonkamer', 'entity_id'))|map(attribute='entity_id')|list}}
