spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

sensor:
  - platform: pocketcasts
    username: !secret pocketcasts_username
    password: !secret pocketcasts_password
