---
homeassistant:
  customize:
    switch.party_lights:
      icon: mdi:party-popper

input_boolean:
  party_lights_on:
    name: "Party Lights - On"
    initial: "off"
    icon: mdi:party-popper

input_number:
  party_lights_speed:
    name: Party Lights - Speed
    unit_of_measurement: seconds
    initial: 15
    min: 3
    max: 60
    step: 1
    icon: mdi:speedometer

script:
  party_lights_animation:
    alias: Party Lights Animation
    sequence:
      - service: switch.turn_off
        target:
          entity_id: switch.adaptive_lighting_all_lights
      - repeat:
          while:
            - condition: state
              entity_id: input_boolean.party_lights_on
              state: "on"
          sequence:
            - service: script.apply_party_lights_scene
            - delay: >
                {{ states("input_number.party_lights_speed") }}
    icon: mdi:party-popper
  apply_party_lights_scene:
    alias: Apply Party Lights Scene
    sequence:
      - service: light.turn_on
        data_template:
          entity_id:
            - light.ceiling_e
            - light.hallway_e
            - light.living_room_lamp
            - light.bedroom_lamp
          rgb_color:
            [
              "{{ (range(0, 255) | random) }}",
              "{{ (range(0, 255) | random) }}",
              "{{ (range(0, 255) | random) }}",
            ]
          brightness: "{{ (range(50, 250) | random) }}"
          transition: 0.1
      - service: light.turn_on
        data_template:
          entity_id:
            - light.ceiling_w
            - light.hallway_w
            - light.bathroom_w
            - light.bed
          rgb_color:
            [
              "{{ (range(0, 255) | random) }}",
              "{{ (range(0, 255) | random) }}",
              "{{ (range(0, 255) | random) }}",
            ]
          brightness: "{{ (range(50, 250) | random) }}"
          transition: 0.1
    icon: mdi:party-popper

switch:
  - platform: template
    switches:
      party_lights:
        value_template: >
          {{ states("input_boolean.party_lights_on") }}
        friendly_name: Party Lights
        turn_on:
          - service: input_boolean.turn_on
            entity_id: input_boolean.party_lights_on
          - service: script.turn_on
            target:
              entity_id: script.party_lights_animation
        turn_off:
          - service: input_boolean.turn_off
            entity_id: input_boolean.party_lights_on
          - service: script.turn_off
            target:
              entity_id: script.party_lights_animation
