---
homeassistant:
  customize:
    automation.reset_scene_before_party_lights:
      icon: mdi:cancel
    switch.party_lights:
      icon: mdi:party-popper
    scene.before_party_lights:
      friendly_name: Party Lights - Return Scene
      icon: mdi:party-popper

logbook:
  exclude:
    entities:
      - input_boolean.party_lights_on
      - script.party_lights_animation

input_boolean:
  party_lights_on:
    name: "Party Lights - On"
    initial: off
    icon: mdi:party-popper

input_number:
  party_lights_speed:
    name: Party Lights - Speed
    unit_of_measurement: seconds
    initial: 15
    min: 3
    max: 60
    step: 1
    icon: mdi:speedometer

script:
  party_lights_animation:
    alias: Party Lights Animation
    sequence:
      - service: switch.turn_off
        target:
          entity_id: switch.adaptive_lighting_all_light_bulbs
      - repeat:
          while:
            - condition: state
              entity_id: input_boolean.party_lights_on
              state: "on"
          sequence:
            - service: script.apply_party_lights_scene
            - delay: >
                {{ states("input_number.party_lights_speed") }}
    icon: mdi:party-popper
  apply_party_lights_scene:
    alias: Apply Party Lights Scene
    sequence:
      - service: light.turn_on
        data:
          entity_id:
            - light.ceiling_e
            - light.living_room_lamp
            - light.hallway_e
            - light.bedroom_lamp
          rgb_color:
            [
              "{{ (range(0, 255) | random) }}",
              "{{ (range(0, 255) | random) }}",
              "{{ (range(0, 255) | random) }}",
            ]
          brightness: "{{ (range(50, 250) | random) }}"
          transition: 0.1
      - service: light.turn_on
        data:
          entity_id:
            - light.ceiling_w
            - light.bookshelf
            - light.hallway_w
            - light.bathroom_w
            - light.bed
          rgb_color:
            [
              "{{ (range(0, 255) | random) }}",
              "{{ (range(0, 255) | random) }}",
              "{{ (range(0, 255) | random) }}",
            ]
          brightness: "{{ (range(50, 250) | random) }}"
          transition: 0.1
    icon: mdi:party-popper

automation:
  - id: reset_scene_before_party_lights_2
    alias: Reset scene.before_party_lights
    mode: single
    trigger:
      - platform: homeassistant
        event: start
    action:
      - service: scene.create
        data:
          scene_id: before_party_lights
          entities:
            automation.reset_scene_before_party_lights:
              state: "on"

switch:
  - platform: template
    switches:
      party_lights:
        value_template: >
          {{ states("input_boolean.party_lights_on") }}
        friendly_name: Party Lights
        turn_on:
          - service: input_boolean.turn_on
            entity_id: input_boolean.party_lights_on
          - service: scene.create
            data:
              scene_id: before_party_lights
              snapshot_entities:
                - switch.adaptive_lighting_all_light_bulbs
                - light.ceiling_e
                - light.ceiling_w
                - light.bookshelf
                - light.living_room_lamp
                - light.hallway_e
                - light.hallway_w
                - light.bathroom_e
                - light.bathroom_w
                - light.bedroom_lamp
                - light.bed
          - service: script.turn_on
            target:
              entity_id: script.party_lights_animation
        turn_off:
          - service: input_boolean.turn_off
            entity_id: input_boolean.party_lights_on
          - service: script.turn_off
            target:
              entity_id: script.party_lights_animation
          - service: scene.turn_on
            target:
              entity_id: scene.before_party_lights
          - service: automation.trigger
            target:
              entity_id: automation.reset_scene_before_party_lights
