---
homeassistant:
  customize:
    automation.flash_lights_on_silent_phone_ring:
      icon: mdi:alarm-bell
automation:
  - id: notify_phone_at_home
    alias: Notify Phone at Home
    mode: single
    trigger:
      - entity_id: sensor.scarif_phone_state
        platform: state
        from: idle
        to: ringing
    condition:
      - condition: template
        value_template: >
          {{ not is_state("sensor.scarif_do_not_disturb_sensor", "Off") or
          states("sensor.scarif_volume_level_ringer") | int < 5 }}
      - entity_id: person.djhanggi
        condition: state
        state: home
    action:
      - service: notify.notify
        data:
          message: scarif is ringing
      - service: switch.turn_on
        target:
          entity_id: switch.party_lights
      - service: notify.mobile_app_scarif
        data:
          command: normal
          message: command_ringer_mode
      - delay:
          seconds: 5
      - service: switch.turn_off
        target:
          entity_id: switch.party_lights
      - service: notify.mobile_app_scarif
        data:
          command: vibrate
          message: command_ringer_mode
