---
homeassistant:
  customize:
    automation.flash_lights_on_silent_phone_ring:
      icon: mdi:alarm-bell

automation:
  - id: flash_lights_on_silent_phone_ring
    alias: Flash Lights On Silent Phone Ring
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.scarif_phone_state
        from: idle
        to: ringing
    condition:
      - condition: template
        value_template: >
          {{ not is_state("sensor.scarif_do_not_disturb_sensor", "Off") or
          states("sensor.scarif_volume_level_ringer") | int < 5 }}
      - condition: state
        entity_id: sensor.djhanggi_at_home
        state: home
    action:
      - service: input_number.set_value
        data:
          value: 3
        target:
          entity_id: input_number.party_lights_speed
      - service: switch.turn_on
        target:
          entity_id: switch.party_lights
      - delay:
          seconds: 10
      - service: switch.turn_off
        target:
          entity_id: switch.party_lights
