input_datetime:
  majesty_palm_sunrise_time:
    name: Majesty Palm Sunrise Time
    has_time: true
    initial: '07:15'
    icon: mdi:weather-sunset-up
  majesty_palm_sunset_time:
    name: Majesty Palm Sunset Time
    has_time: true
    initial: '21:45'
    icon: mdi:weather-night

automation:
  - id: majesty_palm_sunrise
    alias: Majesty Palm Sunrise
    description: Turns on the Majesty Palm light.
    trigger:
      - platform: time
        at: input_datetime.majesty_palm_sunrise_time
    condition: []
    action:
      - service: switch.turn_on
        target:
          entity_id: switch.majesty_palm_light
    mode: single
  - id: majesty_palm_sunset
    alias: Majesty Palm Sunset
    description: Turns off the Majesty Palm light.
    trigger:
      - platform: time
        at: input_datetime.majesty_palm_sunset_time
    condition: []
    action:
      - service: switch.turn_off
        target:
          entity_id: switch.majesty_palm_light
    mode: single
