---
homeassistant:
  customize:
    automation.plant_care:
      icon: mdi:flower
    switch.living_room_plant_light:
      device_class: light
      icon: mdi:flower
    switch.bedroom_plant_light:
      device_class: light
      icon: mdi:flower
    switch.humidifer:
      device_class: switch
      icon: mdi:humidifer

input_datetime:
  plant_sunrise_time:
    name: Plant Sunrise Time
    has_time: true
    initial: "07:15:00"
    icon: mdi:weather-sunset-up
  plant_sunset_time:
    name: Plant Sunset Time
    has_time: true
    initial: "21:45:00"
    icon: mdi:weather-night

automation:
  - id: plant_care
    alias: Plant Care
    description: Turns on plant lighting and humidifers.
    trigger:
      - platform: time
        id: plant_sunrise_trigger
        at: input_datetime.plant_sunrise_time
      - platform: time
        id: plant_sunset_trigger
        at: input_datetime.plant_sunset_time
    action:
      - service_template: >
          {% if trigger.id == "plant_sunrise_trigger" %}
            switch.turn_on
          {% elif trigger.id == "plant_sunset_trigger" %}
            switch.turn_off
          {% else %}
            switch.toggle
          {% endif %}
        target:
          entity_id:
            - switch.living_room_plant_light
            - switch.bedroom_plant_light
            # TODO(djhanggi): Re-enable in the fall.
            # - switch.humidifier
    mode: queued
