---
homeassistant:
  customize:
    automation.plant_care:
      icon: mdi:flower
    switch.living_room_plant_light:
      device_class: light
      icon: mdi:flower
    switch.bedroom_plant_light:
      device_class: light
      icon: mdi:flower

automation:
  - id: plant_care
    alias: Plant Care
    description: Turns on/off plant care entities (lights, etc.).
    trigger:
      - platform: time
        id: plant_sunrise_trigger
        at: input_datetime.morning_start_time
      - platform: time
        id: plant_sunset_trigger
        at: input_datetime.evening_start_time
    action:
      - service: >
          {% if trigger.id == "plant_sunrise_trigger" %}
            switch.turn_on
          {% elif trigger.id == "plant_sunset_trigger" %}
            switch.turn_off
          {% else %}
            switch.toggle
          {% endif %}
        target:
          entity_id:
            - switch.living_room_plant_light
            - switch.bedroom_plant_light
    mode: queued
