---
homeassistant:
  customize:
    automation.air_purifier:
      icon: mdi:air-filter

logbook:
  exclude:
    entities:
      - automation.air_purifier

automation:
  - id: air_purifier
    alias: Air Purifier
    mode: queued
    trigger:
      - platform: state
        entity_id: binary_sensor.location_in_bedroom
      - entity_id: fan.levoit_air_purifier
        platform: state
        to: "on"
      - id: aqi
        entity_id: sensor.levoit_air_purifier_air_quality
        platform: state
    condition:
      - entity_id: person.djhanggi
        condition: state
        state: home
      - condition: template
        value_template: |
          {% set last_trigger_time = state_attr("automation.air_purifier", "last_triggered") | default(0) %}
          {{ 
            trigger.id != "aqi" or 
            ((now() | as_timestamp) - (last_trigger_time | as_timestamp)) > 5 * 60 
          }}
    action:
      - variables:
          percentage: |
            {% set in_bedroom = is_state("binary_sensor.location_in_bedroom", "on") %}
            {% set aqi = states("sensor.levoit_air_purifier_air_quality") | int %}
            {% if not in_bedroom or aqi < 10 %}
              0
            {% elif aqi < 25 %}
              25
            {% elif aqi < 50 %}
              50
            {% elif aqi < 75 %}
              75
            {% else %}
              100
            {% endif %}
      - service: fan.set_percentage
        data:
          percentage: "{{ percentage }}"
        target:
          entity_id: fan.levoit_air_purifier
