---
homeassistant:
  customize:
    automation.purify_bedroom_air:
      icon: mdi:air-filter

automation:
  - id: purify_bedroom_air
    alias: Purify Bedroom Air
    mode: queued
    trigger:
      - id: air_quality_change
        entity_id: sensor.levoit_air_purifier_air_quality
        platform: state
      - id: power_on
        entity_id: fan.levoit_air_purifier
        platform: state
        to: "on"
    condition:
      - entity_id: person.djhanggi
        condition: state
        state: home
    action:
      - variables:
          percentage: |
            {% set aqi = states("sensor.levoit_air_purifier_air_quality") | int %}
            {% if aqi < 10 %}
              0
            {% elif aqi < 25 %}
              25
            {% elif aqi < 50 %}
              50
            {% elif aqi < 75 %}
              75
            {% else %}
              100
            {% endif %}
      - service: fan.set_percentage
        data:
          percentage: "{{ percentage }}"
        target:
          entity_id: fan.levoit_air_purifier
