---
homeassistant:
  customize:
    automation.presence_bathroom:
      icon: mdi:toilet

automation:
  - id: presence_bathroom
    alias: Presence - Bathroom
    mode: queued
    trigger:
      - id: enter
        platform: state
        entity_id: binary_sensor.location_in_bathroom
        to: "on"
      - id: clear
        platform: state
        entity_id: binary_sensor.location_in_bathroom
        to: "off"
    condition:
      - condition: or
        conditions:
          - '{{ trigger.id == "enter" and not is_state("sensor.phase_of_day",
            "Sleeping")}}'
          - '{{ trigger.id == "clear" }}'
    action:
      - service: |
          {% if trigger.id == "enter" %}
            light.turn_on
          {% else %}
            light.turn_off
          {% endif %}
        target:
          entity_id: light.bathroom_lights
