---
homeassistant:
  customize:
    automation.presence_bathroom:
      icon: mdi:toilet

automation:
  - id: presence_bathroom
    alias: Presence - Bathroom
    mode: queued
    trigger:
      - platform: template
        template: |
          {{ 
            is_state("binary_sensor.location_in_bathroom", "on") and 
            not is_state("input_boolean.phase_of_day", "Sleeping")
          }}
        variables:
          service: light.turn_on
      - platform: state
        entity_id: binary_sensor.location_in_bathroom
        to: "off"
        variables: 
          service: light.turn_off
    action:
      - service: '{{ service }}'
        target:
          entity_id: light.bathroom_lights
