---
homeassistant:
  customize:
    automation.presence_bathroom:
      icon: mdi:toilet

automation:
  - id: presence_bathroom
    alias: Presence - Bathroom
    mode: queued
    trigger:
      - platform: state
        entity_id: binary_sensor.location_in_bathroom
    action:
      - service: |
          {% set in_bathroom = is_state("binary_sensor.location_in_bathroom", "on") %}
          {% set is_sleeping = is_state("sensor.phase_of_day", "Sleeping") %}
          {% if in_bathroom and not is_sleeping %}
            light.turn_on
          {% elif not in_bathroom %}
            light.turn_off
          {% endif %}
        target:
          entity_id: light.bathroom_lights
