---
homeassistant:
  customize:
    automation.presence_bathroom:
      icon: mdi:lightbulb-auto

automation:
  - id: presence_bathroom
    alias: Presence - Bathroom
    mode: queued
    trigger:
      - id: enter_bathroom
        platform: state
        entity_id: sensor.latest_location
        to: bathroom
      - id: clear
        platform: template
        value_template: |
          {{ not (
            is_state("sensor.latest_location", "bathroom") 
            or 'bathroom' in states('sensor.latest_locations') | from_json) 
          }}
    action:
      - service: |
          {% set is_sleeping = is_state("sensor.phase_of_day", "Sleeping") %}
          {% if trigger.id == "enter_bathroom" %}
            {% if not is_sleeping %}
              homeassistant.turn_on
            {% endif %}
          {% elif trigger.id == "clear" %}
            homeassistant.turn_off
          {% endif %}
        target:
          entity_id: light.bathroom_lights
