---
homeassistant:
  customize:
    automation.presence_aware_bathroom_lights:
      icon: mdi:lightbulb-auto
    
automation:
  - id: presence_bathroom_lights
    alias: Presence - Bathroom Lights
    mode: single
    trigger:
      - id: enter
        entity_id: binary_sensor.aqara_motion_bathroom
        platform: state
        to: "on"
      - id: exit
        entity_id: binary_sensor.aqara_motion_bathroom
        platform: state
        for:
          minutes: 5
        from: "on"
    action:
      - service: |
          {% set is_sleeping = is_state("sensor.phase_of_day", "Sleeping") %}
          {% if trigger.id == "enter" and not is_sleeping %}
            homeassistant.turn_on
          {% else %}
            homeassistant.turn_off
          {% endif %}
        target:
          entity_id: light.bathroom_lights
