---
homeassistant:
  customize:
    automation.presence_desk_chair:
      icon: mdi:chair-rolling

automation:
  - id: presence_desk_chair
    alias: Presence - Desk Chair
    mode: single
    trigger:
      - entity_id: binary_sensor.aqara_vibration_desk_chair
        platform: state
        to: "on"
    action:
      - if:
          - '{{ is_state("sensor.phase_of_day", "Morning") }}'
        then:
          - service: scene.turn_on
            target:
              entity_id: scene.daytime
          - service: switch.turn_off
            target:
              entity_id: switch.living_room_cam
      - if:
          - '{{ is_state("sensor.phase_of_day", "Morning") or is_state("sensor.phase_of_day", "Daytime") }}'
          - condition: template
            value_template: |
              {% set last_desk_lamp_time = states("sensor.last_desk_lamp_timestamp") %}
              {% set last_midnight = now().replace(hour=0, minute=0, second=0) | as_timestamp %}
              {{ last_desk_lamp_time == "unknown" or last_desk_lamp_time < last_midnight }}
        then:
          - service: switch.turn_on
            target:
              entity_id: switch.desk_lamp
