---
homeassistant:
  customize:
    automation.presence_desk_chair:
      icon: mdi:chair-rolling

automation:
  - id: presence_desk_chair
    alias: Presence - Desk Chair
    mode: single
    trigger:
      - entity_id: binary_sensor.aqara_vibration_desk_chair
        platform: state
        to: "on"
    action:
      - if:
          - entity_id: sensor.phase_of_day
            condition: state
            state: Morning
        then:
          - service: scene.turn_on
            target:
              entity_id: scene.daytime
          - service: switch.turn_off
            target:
              entity_id: switch.living_room_cam
      - if:
          - entity_id: sensor.phase_of_day
            condition: state
            state: 
              - Morning
              - Daytime
          - entity_id: binary_sensor.desk_lamp_used_completely_today
            condition: state
            state: "off"
        then:
          - service: timer.start
            target:
              entity_id: timer.desk_lamp_timer
