---
homeassistant:
  customize:
    automation.presence_leave:
      icon: mdi:location-exit
    automation.presence_return:
      icon: mdi:location-enter
    scene.presence_return_scene:
      friendly_name: Presence - Return Scene
      icon: mdi:location-enter

automation:
  - id: presence_leave
    alias: Presence - Leave
    mode: single
    trigger:
      - id: presence
        platform: state
        entity_id: person.djhanggi
        from: home
        to: not_home
    variables:
      light_entities: '{{ states("sensor.active_lights") | from_json }}'
      other_snapshot_entities:
        - remote.harmony
        - switch.vornado_fan
        - fan.dyson_fan
        - fan.dyson_heater_fan
      non_snapshot_entities:
        - switch.desk_lamp
        - switch.sunlight_lamp
        - switch.kitchen_lights
    action:
      - if:
          - '{{ trigger.id == "presence" }}'
        then:
          - service: scene.create
            data:
              scene_id: presence_return_scene
              snapshot_entities:
                "{{ light_entities + other_snapshot_entities }}"
      - service: scene.apply
        data:
          entities: |
            {
              {% for entity_id in (light_entities + other_snapshot_entities + non_snapshot_entities) %}
                "{{ entity_id }}": { 
                  "state": "off",
                },
              {% endfor %}
            }
      - if:
          - '{{ not is_state_attr("media_player.spotify_djhanggi", "source",
            "scarif") }}'
        then:
          - service: media_player.media_pause
            target:
              entity_id: media_player.spotify_djhanggi
  - id: presence_return
    alias: Presence - Return
    mode: single
    trigger:
      - platform: state
        entity_id: person.djhanggi
        from: not_home
        to: home
    action:
      - scene: scene.presence_return_scene
      - if:
          - '{{ is_state("sensor.phase_of_day", "Evening") }}'
        then:
          - service: automation.trigger
            target:
              entity_id: automation.evening
      - service: scene.create
        data:
          scene_id: presence_return_scene
          entities:
            automation.presence_return:
              state: "on"
