---
homeassistant:
  customize:
    automation.presence_kitchen:
      icon: mdi:fridge

automation:
  - id: presence_kitchen
    alias: Presence - Kitchen
    mode: queued
    trigger:
      - platform: state
        entity_id: binary_sensor.location_in_kitchen
    action:
      - service: |
          {% set in_kitchen = is_state("binary_sensor.location_in_kitchen", "on") %}
          {% set is_daytime = is_state("sensor.phase_of_day", "Daytime") %}
          {% if in_kitchen and is_daytime %}
            switch.turn_on
          {% else %}
            switch.turn_off
          {% endif %}
        target:
          entity_id: switch.kitchen_lights
