---
homeassistant:
  customize:
    automation.presence_kitchen_stove:
      icon: mdi:thermometer
    sensor.kitchen_temperature_derivative:
      icon: mdi:thermometer

input_number:
  kitchen_temperature_derivative_threshold:
    name: Kitchen Temperature Derivative Threshold
    icon: mdi:thermometer
    min: 0
    max: 2
    initial: 0.01

sensor:
  - name: Kitchen Temperature Derivative
    platform: derivative
    source: sensor.aqara_temperature_kitchen_temperature
    time_window: "00:02:00"
    unit_time: min

automation:
  - id: presence_kitchen_stove
    alias: Presence - Kitchen Stove
    mode: single
    trigger:
      - id: clear
        entity_id: binary_sensor.aqara_motion_kitchen
        platform: state
        for:
          minutes: 2
        from: "on"
        to: "off"
    condition:
      - '{{ states("sensor.kitchen_temperature_derivative") >
        states("input_number.kitchen_temperature_derivative_threshold") }}'
    action:
      - repeat:
          sequence:
            - service: notify.notify
              data:
                data:
                  tag: automation.presence_kitchen_stove
                message: Stove may be running!
            - delay:
                minutes: 2
          until:
            - '{{ is_state("binary_sensor.aqara_motion_kitchen", "on") }}'
            - '{{ states("sensor.kitchen_temperature_derivative") < 0 }}'
      - service: notify.notify
        data:
          data:
            tag: automation.presence_kitchen_stove
          message: clear_notification
