---
homeassistant:
  customize:
    automation.presence_kitchen_lights:
      icon: mdi:lightbulb-auto
    sensor.kitchen_temperature_derivative:
      icon: mdi:thermometer

sensor:
  - name: Kitchen Temperature Derivative
    platform: derivative
    source: sensor.aqara_temperature_kitchen_temperature
    time_window: "00:05:00"
    unit_time: min

automation:
  - id: presence_kitchen_lights
    alias: Presence - Kitchen Lights
    mode: single
    trigger:
      - id: enter
        entity_id: binary_sensor.aqara_motion_kitchen
        platform: state
        to: "on"
      - id: clear
        entity_id: binary_sensor.aqara_motion_kitchen
        platform: state
        for:
          minutes: 5
        from: "on"
    action:
      - service: |
          {% set is_evening = is_state("sensor.phase_of_day", "Evening") %}
          {% set is_sleeping = is_state("sensor.phase_of_day", "Sleeping") %}
          {% if trigger.id == "enter" %}
            {% if not (is_evening or is_sleeping) %}
              homeassistant.turn_on
            {% endif %}
          {% elif trigger.id == "clear" %}
            homeassistant.turn_off
          {% endif %}
        target:
          entity_id: switch.kitchen_lights
