---
homeassistant:
  customize:
    automation.presence_kitchen:
      icon: mdi:fridge

automation:
  - id: presence_kitchen
    alias: Presence - Kitchen
    mode: queued
    trigger:
      - platform: template
        value_template: |
          {{ 
            is_state("binary_sensor.location_in_kitchen", "on") and 
            is_state("sensor.phase_of_day", ["Morning", "Daytime"])
          }}
        variables:
          service: switch.turn_on
      - platform: state
        entity_id: binary_sensor.location_in_kitchen
        to: "off"
        variables: 
          service: switch.turn_off
    action:
      - service: '{{ service }}'
        target:
          entity_id: switch.kitchen_lights
