---
homeassistant:
  customize:
    automation.presence_kitchen:
      icon: mdi:fridge

automation:
  - id: presence_kitchen
    alias: Presence - Kitchen
    mode: queued
    trigger:
      - id: enter
        platform: state
        entity_id: binary_sensor.location_in_kitchen
        to: "on"
      - id: clear
        platform: state
        entity_id: binary_sensor.location_in_kitchen
        to: "off"
    condition:
      - condition: or
        conditions:
          - '{{ trigger.id == "enter" and is_state("input_boolean.is_sleeping",
            "off") }}'
          - '{{ trigger.id == "clear" }}'
    action:
      - service: |
          {% if trigger.id == "enter" %}
            switch.turn_on
          {% else %}
            switch.turn_off
          {% endif %}
        target:
          entity_id: switch.kitchen_lights
