- id: update_at_home
  alias: Update At Home
  description: Updates At Home.
  trigger:
  - platform: state
    entity_id: person.djhanggi
  condition: []
  action:
    - service_template: >
        {% if is_state('person.djhanggi', 'home') %}
          input_boolean.turn_on
        {% else %}
          input_boolean.turn_off
        {% endif %}
        target:
          entity_id: input_boolean.at_home
  mode: single
